# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG

DB += table-csv.db
DB += table-csv2.db
DB += table-csv2-rows.db
DB += table-src-rows.db
DB += table-rows.db
DB += table-sim.db
DB += table-soft.db
DB += table-stat.db

include $(TOP)/configure/RULES

